version: "2"
services:
  server:
    container_name: server
    build: server
    restart: always
    ports:
      - "808:8080"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - app-net
  mongodb:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - ./data-node:/data/db
      - ./dbconfig:/data/configdb
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
